### ISSUE TITLE
chore: cron jobs

### ISSUE THREAD

**Issue by Carl-Tabuso** [POWERLANE-TEAM/emplo-hrms#201]
### Task Schedulers

- [x] Command that creates a new record for payroll period.
- [x] Command that execute daily, which programatically fetch and persist the attendance logs to the database and clearing them aftewards in the biometric machine.
- [ ] Command that execute every January 1 to reset the service incentive leave credits of eachemployee.
- [x] Command that clears the activity log. I don't know if this should be set annually to execute.
- [x] Command that executes daily which checks and permanently deletes employee records who are already separated for 4 years.
- [x] Command that executes daily to backup the database.
- [x] Command that generates the payroll summary for `payroll_summaries` table
- [x] Command that executes daily to remove applicants who are rejected for more or exactly than 30 days.

**Comment by Carl-Tabuso** [comment]
closed by #286
