### ISSUE TITLE
Tracker: To-Do Back-Ends

### ISSUE THREAD

**Issue by biellamariscotes** [POWERLANE-TEAM/emplo-hrms#74]
> [!IMPORTANT]  
> ### Check the linked PR each issues for the front-end.
>
> Back-end Completion Legends:
> - ✅ completed
> - 🔄 ongoing, being coded.
> - ❗ still not started.
> - ⚠️incomplete.

<hr>

### AI

- [x] Resume Conversion (Apply) ✅
- [x] #230 🔄

<hr>

### Modules

**Recruitment Management**

- [x] #98 ✅ [refactor/heavily bugged with the soc med APIs]
- [x] #117 🔄
- [x] #136 ⚠️[revamp in adding qualifications]

<hr>

**Employee Management**
- [x] #155 ⚠️ [revamp/revisit]
- [x] #202 ❗ **HIGH PRIO**

<hr>

**Attendance Tracking**
- [x] #130 ✅ [improvement]
- [x] #209 ⚠️ **HIGH PRIO**
- [x] #88  ❗
<hr>

**Leave Management**
- [x] #123 ⚠️
- [x] #88  ❗
<hr>

**Document Management**
- [x] #156 ❗ **HIGH PRIO**
- [x]  Documents Page ❗
- [x] #226 ❗
<hr>

**Employee Relations**
- [x] #134 ✅
- [x] #135 ✅

<hr>

**Performance Management**
- [x] #118 ⚠️ [approvals]
- [x] #154 ❗

<hr>

**System-Related**

- [x] #198 ⚠️**HIGH PRIO**
- [x] #207 ❗**HIGH PRIO**
- [x] #153 ❗
- [x] Dashboard - HR ❗

<hr>

### All Users
- [x] #168 ❗
- [x] #82 ❗ **HIGH PRIO**
- [x] #110 ❗
- [x] #197 ❗
- [x] #227 ❗
<hr>

### Head Admin
- [x] #89 [least prio]  ❗ [front-end]

### Revisits

- #84
<hr>

### Removals
- Add Attendance back in eval-results-navs.blade.php
